Jets homepage basic
KaskMIL/book-a-jet-front-end pull request #20
Opened 2022-10-20 22:27 UTC by KaskMIL

# In this new Pull Request I'm adding the following features:
- Add react-router-dom, react-bootstrap and bootstrap dependencies.
- Add Routes to App.js.
- Create a Main component that will contain the jets cards/component.
- Create a Nav component with a first approach for the navbar, with activeLink function to let the user knows in which link he is.
- Basic styling for a better view.
- Commented redux code because it was generating conflicts.

2022-10-20 23:20 UTC, mikemtzp requested changes
# Status: Changes Required♻️ 
Hi, @KaskMIL  

You have done a great job so far!👏
There are some issues that you still need to work on to go to the next project. You are almost there!💪

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif" width="300"/>

## Highlights🎯
- Good job building the Navbar.
- Proper build of the Home page component

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 23:20 UTC, mikemtzp commented on src/assets/styles/nav.scss
> +      padding-left: 10px;
As the app is going to have a responsive design for mobile and desktop by using `@media` rules I believe we can improve the CSS if we stick to `em` units. Here I share an [article ](https://dev.to/romankhan/a-complete-guide-of-responsive-web-design-using-css-rem-and-em-units-4j6k#:~:text=Always%20use%20the%20em%20unit,adjust%20based%20on%20font%20size.)about it. 👍🏼

2022-10-20 23:20 UTC, mikemtzp commented on src/assets/styles/nav.scss
> +  padding: 0;
Good job tackling the padding and the margin to 0. To keep the code DRY I think we could add these lines to the general `index.css` file so they apply to the whole app. also, it would be nice to add a `box-sizing: border-box;` property

2022-10-20 23:20 UTC, mikemtzp commented on src/components/nav/Nav.js
> +  };
Great work defining the active style on the Navbar. The best practice is to keep style separated from the logic of a component I think we can keep our code at its best by moving this styling into the `nav.scss`. 👏🏼

2022-10-20 23:20 UTC, mikemtzp commented on src/components/nav/Nav.js
> +        </li>
I think the way to achieve removing the style from the current component is by inserting the conditional logic into the `className` property. I share with you a [quick tutorial](https://www.youtube.com/watch?v=6fLp3mUB6b8&t=172s) that might help you. let me know if you can achieve this. 😃

2022-10-21 12:15 UTC, KaskMIL commented
Hi @mikemtzp,
Thanks for the review, I implemented the changes suggested.
Happy coding!

2022-10-25 15:02 UTC, mikemtzp approved these changes
# Status: Approved💯
Hi, @KaskMIL  

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
🎉Congratulations! 🎉

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" width="400"/>

## Highlights🎯
- Great implementation of the navbar
- Routing is working correctly
- Dummy data displays correctly

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 15:02 UTC, merged